language: node_js
sudo: false
dist: xenial
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "4"
  - "6"
  - "7"
before_install:
  - npm config set registry https://:2017-05-25T18%3A52%3A28.462Z@time-machines-npm.sealsecurity.io/
install:
  - npm install
  - npm install hiredis
script:
  - npm run coverage -- --no-colors
