name: seal-build

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '7.10.0'
      - name: Pack
        run: |
          node --version
          npm --version
          rm -rf .github
          npm pack
          ls -l redis-parser-3.0.0.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: redis-parser-3.0.0
          path: redis-parser-3.0.0.tgz
